(function(){
  const pages=['pse.html','bindungscode.html','edelgasregel.html','ionenbildung.html','ionengitter.html','salze.html','atombindung.html','lewis.html','metallbindung.html','metalleigenschaften.html','bindungsdetektiv.html','finale.html'];
  const labels=['PSE','Bindungsart','Bindungsmodell','Struktur','Eigenschaften'];
  function currentMission(){const file=location.pathname.split('/').pop();return file==='metall-abschlusstest.html'?10:['elektronegativitaet.html','reaktionsgleichungen-atombindung.html','atombindung-abschlusstest.html'].includes(file)?8:pages.indexOf(file)+1}
  function renderNavigation(){
    const host=document.querySelector('[data-navigation]');if(!host)return;
    const mission=currentMission(),file=location.pathname.split('/').pop(),back=file==='metall-abschlusstest.html'?'metalleigenschaften.html':file==='elektronegativitaet.html'?'lewis.html':file==='reaktionsgleichungen-atombindung.html'?'elektronegativitaet.html':file==='atombindung-abschlusstest.html'?'reaktionsgleichungen-atombindung.html':file==='metallbindung.html'?'atombindung-abschlusstest.html':file==='arbeitsblatt-bindungen.html'?'bindungscode.html':mission>1?pages[mission-2]:'index.html';
    if(file&&file!=='index.html')BindungenProgress.setLastPosition(file);
    host.innerHTML='<nav class="site-nav"><a class="nav-back" href="'+back+'">← Zurück</a><a class="brand" href="index.html">CHEMISCHE BINDUNGEN</a><span class="course-title">Chemische Bindungen</span></nav><section class="progress-shell" id="progress"><div class="progress-top"><span>Lernfortschritt</span><strong data-progress-text>0 / 12</strong></div><div class="progress-track"><div class="progress-fill" data-progress-fill></div></div><div class="progress-steps">'+labels.map((x,i)=>'<span data-step="'+i+'">'+x+'</span>').join('')+'</div></section>';
    updateProgress();
  }
  function updateProgress(){const p=BindungenProgress.loadProgress(),n=p.completedMissions.length;document.querySelectorAll('[data-progress-text]').forEach(x=>x.textContent=n+' / 12');document.querySelectorAll('[data-progress-fill]').forEach(x=>x.style.width=(n/12*100)+'%');const file=location.pathname.split('/').pop(),mission=currentMission();const step=file==='arbeitsblatt-bindungen.html'?1:mission?Math.min(4,Math.floor((mission-1)*5/12)):-1;document.querySelectorAll('[data-step]').forEach((x,i)=>x.classList.toggle('active',i===step))}
  function updateIndexResume(){const file=location.pathname.split('/').pop();if(file&&file!=='index.html')return;const progress=BindungenProgress.loadProgress(),target=progress.lastPosition||'pse.html';console.log('[Navigation DEBUG] Cloud lastPosition:',progress.lastPosition);console.log('[Navigation DEBUG] Weiterlernen-Ziel:',target);const continueLink=document.querySelector('#continue-learning');if(continueLink)continueLink.href=target;const start=document.querySelector('#start');if(start)start.href=target}
  function guardMission(){const file=location.pathname.split('/').pop(),p=BindungenProgress.loadProgress();if(file==='arbeitsblatt-bindungen.html'&&!p.completedMissions.includes(2)){location.replace('bindungscode.html');return}if(file==='ionenbildung.html'&&!p.arbeitsblattBindungenBestanden){location.replace('arbeitsblatt-bindungen.html?locked=1');return}if(file==='metallbindung.html'&&!p.atombindungOnlineTestBestanden&&!p.completedMissions.includes(9)){location.replace('atombindung-abschlusstest.html');return}const n=currentMission();if(n>1&&!BindungenProgress.isMissionUnlocked(n)){location.replace('index.html?locked='+n)}}
  document.addEventListener('DOMContentLoaded',()=>{renderNavigation();guardMission();updateIndexResume();setTimeout(()=>{const p=BindungenProgress.loadProgress(),start=document.querySelector('#start');if(start&&p.completedMissions.includes(2)&&!p.completedMissions.includes(3)){start.textContent='WEITERLERNEN';start.href='arbeitsblatt-bindungen.html'};if(start&&p.completedMissions.includes(8)&&!p.atombindungOnlineTestBestanden){start.textContent='WEITERLERNEN';start.href=p.elektronegativitaetAbgeschlossen?'reaktionsgleichungen-atombindung.html':'elektronegativitaet.html'};if(start&&p.completedMissions.includes(10)){start.textContent='WEITERLERNEN';start.href='metall-abschlusstest.html'};updateIndexResume()},0)});window.addEventListener('progresschanged',()=>{updateProgress();updateIndexResume()});document.addEventListener('bindungen-progress-ready',updateIndexResume);
})();
