(function(){
  const KEY='chemieBindungenProgress',VERSION=2;
  let firebaseReady=window.BindungenFirebaseReady;
  if(!firebaseReady){const script=document.createElement('script');script.src='js/firebase-runtime.js';document.head.appendChild(script);firebaseReady=new Promise(resolve=>{const wait=()=>window.BindungenFirebaseReady?window.BindungenFirebaseReady.then(resolve):setTimeout(wait,0);wait()})}
  let cloudReady=false,cloudTimer=null,pendingCloudProgress=null,hydratePromise=null,cloudWritePromise=null;
  let progressReadyResolve;
  window.BindungenProgressReady=new Promise(resolve=>{progressReadyResolve=resolve});
  const MODULE_IDS=['pse','bindungscode','ionenbindung','salze','atombindung','metallbindung'];
  const defaults=()=>({version:VERSION,completedMissions:[],currentMission:1,unlockedKnowledge:[],lastPosition:null,modules:Object.fromEntries(MODULE_IDS.map(id=>[id,{}]))});
  const clone=value=>JSON.parse(JSON.stringify(value));
  const isObject=value=>value&&typeof value==='object'&&!Array.isArray(value);
  const merge=(base,extra)=>{if(!isObject(extra))return base;Object.entries(extra).forEach(([key,value])=>{if(isObject(value)&&isObject(base[key]))merge(base[key],value);else if(value!==undefined)base[key]=clone(value)});return base};
  const moduleForLegacy=key=>({covalentLearning:'atombindung',lewisLearning:'atombindung',elektronegativitaetAbgeschlossen:'atombindung',reaktionsgleichungenAbgeschlossen:'atombindung',atombindungOnlineTestBestanden:'atombindung',atombindungTestBestesErgebnis:'atombindung',atombindungAbschlussVersion:'atombindung',metallLearning:'metallbindung',metallbindungFreigeschaltet:'metallbindung',metallOnlineTestBestanden:'metallbindung',metallTestBestesErgebnis:'metallbindung',metallAbschlussVersion:'metallbindung',salzZuordnungAbgeschlossen:'salze',salzOnlineTestBestanden:'salze',salzAbschlussVersion:'salze',arbeitsblattBindungenBestanden:'salze'}[key]);
  function migrate(raw){const source=isObject(raw)?raw:{};if(source.version===VERSION){const current=merge(defaults(),source);MODULE_IDS.forEach(id=>{if(!isObject(current.modules[id]))current.modules[id]={}});return current}const migrated=merge(defaults(),source);migrated.version=VERSION;MODULE_IDS.forEach(id=>{if(!isObject(migrated.modules[id]))migrated.modules[id]={}});Object.entries(source).forEach(([key,value])=>{const moduleId=moduleForLegacy(key);if(moduleId)migrated.modules[moduleId][key]=clone(value)});return migrated}
  function loadProgress(){let raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}const progress=migrate(raw);if(raw.version!==VERSION){try{localStorage.setItem(KEY,JSON.stringify(progress))}catch{}}return clone(progress)}
  function hasLocalProgress(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');return isObject(raw)&&raw.version===VERSION}catch{return false}}
  function currentUid(){try{return JSON.parse(localStorage.getItem('chemieBindungenDevAuth')||'null')?.uid||null}catch{return null}}
  function cloudDoc(){const uid=currentUid();return uid?firebaseReady.then(runtime=>runtime?.db.collection('students').doc(uid)):Promise.resolve(null)}
  async function writeCloudProgress(progress){if(cloudWritePromise)return cloudWritePromise;cloudWritePromise=(async()=>{const uid=currentUid();const doc=await cloudDoc();if(!doc){console.error('[Firestore] Kein Dokumentpfad verfügbar',uid);pendingCloudProgress=clone(progress);return}try{console.log('[Firestore DEBUG] Zu speichernder Fortschritt:',clone(progress));console.log('[Firestore] Fortschritt wird gespeichert',doc.path);await doc.set({version:VERSION,progress:clone(progress),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});console.log('[Firestore] Fortschritt gespeichert',doc.path)}catch(error){pendingCloudProgress=clone(progress);console.error('[Firestore] Speichern fehlgeschlagen',doc.path,error.code,error.message,error)}})();try{return await cloudWritePromise}finally{cloudWritePromise=null}}
  function queueCloudSave(progress){if(!cloudReady){pendingCloudProgress=null;console.log('[Firestore] Cloud noch nicht bereit – lokaler Fortschritt bleibt lokal');return}pendingCloudProgress=clone(progress);clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>{const pending=pendingCloudProgress;pendingCloudProgress=null;writeCloudProgress(pending)},250)}
  function flushPendingCloudSave(){if(!cloudReady||!pendingCloudProgress)return;const pending=pendingCloudProgress;pendingCloudProgress=null;console.log('[Firestore] Cloud jetzt bereit – vorgemerkter Fortschritt wird gespeichert');clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>writeCloudProgress(pending),0)}
  function saveProgress(progress){const normalized=migrate(progress);localStorage.setItem(KEY,JSON.stringify(normalized));console.log('[Progress DEBUG] localStorage gespeichert',clone(normalized.modules));queueCloudSave(normalized);window.dispatchEvent(new Event('progresschanged'));return clone(normalized)}
  function announceProgressReady(progress){const ready=clone(progress);console.log('[Progress Restore] Cloud-Fortschritt bereit');progressReadyResolve?.(ready);document.dispatchEvent(new CustomEvent('bindungen-progress-ready',{detail:ready}))}
  async function hydrateFromCloud(){if(hydratePromise)return hydratePromise;hydratePromise=(async()=>{const runtime=await firebaseReady;const uid=currentUid();if(!runtime){console.error('[Firestore] Synchronisation nicht gestartet: Firebase Runtime fehlt.');const progress=loadProgress();announceProgressReady(progress);return progress}if(!uid||!runtime.auth.currentUser){console.error('[Firestore] Synchronisation wartet: Firebase Auth-Nutzer/UID noch nicht bereit.');return loadProgress()}const path='students/'+uid;const localExists=hasLocalProgress();if(localExists)console.log('[Progress Local] Lokaler Lernstand vorhanden – wird verwendet');console.log('[Firestore] Dokument wird geladen',path);try{const doc=runtime.db.collection('students').doc(uid);const snap=await doc.get();if(snap.exists&&snap.data().progress){console.log('[Firestore] Dokument vorhanden, Fortschritt wird geladen',path);const cloudProgress=migrate(snap.data().progress);console.log('[Firestore DEBUG] Geladener Cloud-Fortschritt:',clone(cloudProgress));if(localExists){console.log('[Progress Local] Cloud-Stand überschreibt lokalen Lernstand NICHT');const progress=loadProgress();cloudReady=true;pendingCloudProgress=null;console.log('[Firestore] Cloud bereit');announceProgressReady(progress);return progress}localStorage.setItem(KEY,JSON.stringify(cloudProgress));console.log('[Firestore DEBUG] Lokaler Fortschritt nach Cloud-Übernahme:',loadProgress());cloudReady=true;pendingCloudProgress=null;console.log('[Firestore] Cloud bereit');window.dispatchEvent(new Event('progresschanged'));announceProgressReady(cloudProgress);return clone(cloudProgress)}console.log('[Firestore] Dokument nicht vorhanden',path);const progress=loadProgress();console.log('[Firestore DEBUG] Zu speichernder Fortschritt:',clone(progress));console.log('[Firestore] Dokument wird erstellt',path);await doc.set({version:VERSION,progress,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});console.log('[Firestore] Dokument erstellt',path);cloudReady=true;pendingCloudProgress=null;console.log('[Firestore] Cloud bereit');announceProgressReady(progress);return progress}catch(error){console.error('[Firestore] Laden/Erstellen fehlgeschlagen',path,error.code,error.message,error);cloudReady=false;const progress=loadProgress();announceProgressReady(progress);return progress}finally{hydratePromise=null}})();return hydratePromise}
  firebaseReady.then(runtime=>{if(runtime)runtime.auth.onAuthStateChanged(user=>{if(user){console.log('[Firebase Auth] bestehende Sitzung erkannt, UID:',user.uid);hydrateFromCloud()}})});
  function patchProgress(changes){const progress=loadProgress();merge(progress,changes);return saveProgress(progress)}
  function getModuleProgress(moduleId){return clone(loadProgress().modules[moduleId]||{})}
  function setModuleProgress(moduleId,changes){if(!MODULE_IDS.includes(moduleId))throw new Error('Unbekannte Modul-ID: '+moduleId);const progress=loadProgress();if(!isObject(progress.modules[moduleId]))progress.modules[moduleId]={};merge(progress.modules[moduleId],changes);return saveProgress(progress)}
  function setSectionProgress(moduleId,sectionId,changes){const moduleProgress=getModuleProgress(moduleId);if(!isObject(moduleProgress.sections))moduleProgress.sections={};if(!isObject(moduleProgress.sections[sectionId]))moduleProgress.sections[sectionId]={};merge(moduleProgress.sections[sectionId],changes);return setModuleProgress(moduleId,moduleProgress)}
  function setTestResult(moduleId,result){return setSectionProgress(moduleId,'test',result)}
  function completeTask(moduleId,taskId,details={}){console.log('[Progress DEBUG] completeTask aufgerufen:',moduleId,taskId,'cloudReady=',cloudReady);const progress=loadProgress();if(!isObject(progress.modules[moduleId]))progress.modules[moduleId]={};if(!isObject(progress.modules[moduleId].tasks))progress.modules[moduleId].tasks={};const previous=progress.modules[moduleId].tasks[taskId];if(previous?.completed){console.log('[Progress DEBUG] Aufgabe war bereits abgeschlossen:',moduleId,taskId);return progress}if(!isObject(details))details={};progress.modules[moduleId].tasks[taskId]=Object.assign({},details,{completed:true});console.log('[Progress DEBUG] Progress nach completeTask:',clone(progress));console.log('[Progress] Aufgabe abgeschlossen: '+moduleId+'/'+taskId);return saveProgress(progress)}
  function setLastPosition(position){if(typeof position!=='string')return loadProgress();return patchProgress({lastPosition:position.split('/').pop()})}
  function completeMission(number,knowledge){const progress=loadProgress();if(!progress.completedMissions.includes(number))progress.completedMissions.push(number);progress.currentMission=Math.max(progress.currentMission,Math.min(12,number+1));if(knowledge&&!progress.unlockedKnowledge.includes(knowledge))progress.unlockedKnowledge.push(knowledge);return saveProgress(progress)}
  function resetProgress(){localStorage.removeItem(KEY);window.dispatchEvent(new Event('progresschanged'))}
  function isMissionUnlocked(number){const progress=loadProgress();return number===1||progress.completedMissions.includes(number-1)||progress.completedMissions.includes(number)}
  window.BindungenProgress={loadProgress,getProgress:loadProgress,saveProgress,patchProgress,getModuleProgress,setModuleProgress,setSectionProgress,setTestResult,completeTask,setLastPosition,completeMission,isMissionUnlocked,resetProgress,hydrateFromCloud,isCloudReady:()=>cloudReady,KEY,VERSION,MODULE_IDS};
})();
